.TH GTTLVUNDUMP 1
.\"
.\"
.\"
.SH NAME
\fBgttlvundump \fR- A tool for constructing TLV file from gttlvdump style input.
.\"
.\"
.SH SYNOPSIS
.\"
.HP 4
\fBgttlvundump \fR[\fB-h\fR] \fR[\fB-v\fR] [\fItlvfile\fR]...
.LP
.\"
.\"
.SH DESCRIPTION
.\"
gttlvundump is a tool that constructs a binary TLV file from gttlvdump style input. Input is read from \fIstdin \fRif input file is not specified. When multiple input files are specified the result is concatenated starting from the first (left-most) file. The output is dumped to the \fIstdout\fR.
.LP
See \fBgttlvdump\fR(1) to learn about the expected format. It must be noted that only basic output format of \fBgttlvdump\fR is accepted as input.
.\"
.\"
.SH OPTIONS
.\"
.TP
\fB-h\fR
Prints help text to \fIstdout\fR.
.\"
.TP
\fB-v\fR
TLV utility package version.
.\"
.SH EXAMPLES
.\"
.TP 2
\fB1
\fRGenerate a TLV file from the given input file and dump the result with gttlvdump:
.LP
.RS 4
File \fItest.tlv\fR contains following TLV structure description.
.LP
TLV[1000]:
  TLV[01]:
    TLV[01]:0a
    TLV[01]:0b

.HP 4
\fBgttlvundump \fItest.tlv \fR| \fBgttlvdump\fR
.RE
.\"
.TP 2
\fB2
\fRTo concatenate two TLV's described in a.tlv and b.tlv and dump the result with gttlvdump: 
.LP
.RS 4
.HP 4
\fBgttlvundump \fIa.tlv \fIb.tlv \fR| \fBgttlvdump\fR
.RE


.LP
.\"
.SH AUTHOR
.LP
Guardtime AS, http://www.guardtime.com/
.LP
.SH SEE ALSO
.LP
\fBgttlvdump\fR(1), \fBgttlvgrep\fR(1), \fBgttlvwrap\fR(1), \fBtlv\fR(5), \fBtlv-desc\fR(5)
